### PR TITLE
fix(app): Prevent ReadMore component from hiding bulk delete add/remove toggle

### LINKED ISSUE #2602: Bulk delete icons missing
**Describe the bug**

Bulk delete icons are missing. I can find the span in the DOM, but its computed size is 0x0 px.

**To Reproduce**

Example: https://openneuro.org/datasets/ds002893

**Screenshots**
on-missing_bulk_delete

**Desktop (please complete the following information):**
- OS: Ubungu
- Browser: Brave
- Version: Recent

### PR DESCRIPTION
**Pull request by nellh**
Fix #2602

### CODE REVIEW

File: packages/openneuro-components/src/read-more/ReadMore.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ export const ReadMore = ({
 
           <section>
             {children}
-            <label htmlFor={id}>
+            <label htmlFor={id} className="expand-collapse">
```
Comment (effigies) [inline packages/openneuro-components/src/read-more/ReadMore.tsx:36]: I guess `className` instead of `class` is because this is technically Javascript even though it looks a lot like HTML?

Comment (nellh) [reply packages/openneuro-components/src/read-more/ReadMore.tsx:36]: Yes, it's a convention used by React because of the potential keyword conflict. Alternatives like Preact just use `class=""`.

**Review by effigies — APPROVED** [review]
Either way, looks like it should do the right thing, given that `<article className="has-read-more readmore-file-tree">` appears here and `<article class="has-read-more readmore-file-tree">` shows up in the rendered page.
