### PR TITLE
Drop cron dependency and use locking to send notifications.

### LINKED ISSUE #1750: Comment notification emails throw "failed to save mailgun identifier"
**Describe the bug**
```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('failed to save mailgunIdentifier <....@openneuro.org>')
    at Function.emit (events.js:304:17)
    at Function.EventEmitter.emit (domain.js:482:12)
    at /srv/node_modules/mongoose/lib/model.js:4624:13
    at model.<anonymous> (/srv/node_modules/mongoose/lib/model.js:437:7)
    at /srv/node_modules/kareem/index.js:315:21
    at next (/srv/node_modules/kareem/index.js:209:27)
    at /srv/node_modules/kareem/index.js:182:9
    at /srv/node_modules/kareem/index.js:499:38
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

This doesn't seem to prevent the email from being sent but it does prevent future email replies.

**To Reproduce**
1. Create a new comment on a dataset
2. The API will throw this error once sending is scheduled

**Expected behavior**
It should be possible to reply to a comment via email.

### PR DESCRIPTION
**Pull request by nellh**
Also catches a spurious error for failure to save mailgunIdentifier.

Fixes #1750 and #1175

### CODE REVIEW

File: packages/openneuro-server/src/libs/notifications.js [hunk 1]
```diff
@@ -340,40 +338,39 @@ const notifications = {
...
           }
-        })
-      },
-      null,
-      true,
-      'America/Los_Angeles',
-    )
+        }
+      })
+    }, 60)
```
Comment (david-nishi) [inline packages/openneuro-server/src/libs/notifications.js]: Currently set to 60 ms instead of the intended hour.

**Review by david-nishi — CHANGES_REQUESTED** [review]

**Review by david-nishi — APPROVED** [review]
