### PR TITLE
fix(app): Link to snapshot download page from snapshots

### LINKED ISSUE #2526: Snapshot download link does not link to snapshot download page
**Describe the bug**
This is linking to the draft download page.

**To Reproduce**
1. Visit any snapshot
2. Click download

### PR DESCRIPTION
**Pull request by nellh**
Replaces DatasetTools isSnapshot with a snapshot id to allow for this link to work.

Fixes #2526

### CODE REVIEW

File: packages/openneuro-components/src/dataset/DatasetTools.tsx [hunk 1]
```diff
@@ -89,7 +90,9 @@ export const DatasetTools = ({
         </Tooltip>
       )}
       <span>
-        <Link className="dataset-tool" to={`/datasets/${datasetId}/download`}>
+        <Link
+          className="dataset-tool"
+          to={`/datasets/${datasetId}/versions/${snapshotId}/download`}>
```
Comment (rwblair) [inline packages/openneuro-components/src/dataset/DatasetTools.tsx]: If I'm logged in and navigate to a published dataset I own it defaults to the draft view and the snapshotId is undefined, Following through with the download link the api produces a 5xx error.

**Review by rwblair — CHANGES_REQUESTED** [review]

File: packages/openneuro-components/src/dataset/DatasetTools.tsx (hunk 1 above)
Comment (nellh) [reply packages/openneuro-components/src/dataset/DatasetTools.tsx]: Added a fix for this with new test coverage for the issue.

**Review by rwblair — APPROVED** [review]
